spec:
  inputs:
    git_strategy:
      options: ['fetch', 'clone', 'none']
      default: 'fetch'
    git_depth:
      default: 200
---

image: $CI_REGISTRY/baikal-arm/kernel:1.0

stages:
  - build
  - package

variables:
  GIT_STRATEGY: $[[ inputs.git_strategy ]]
  GIT_DEPTH: $[[ inputs.git_depth ]]

.build_kernel_template: &build_kernel_dfn
  stage: build
  tags:
    - amd64
  script:
    - rm -f linux-*.deb linux-*.buildinfo linux-*.changes
    - rm -rf ./build ./release
    - mkdir -p release/${CPU_TYPE}
    - make ARCH=arm64 CROSS_COMPILE=/usr/bin/aarch64-linux-gnu- O=./build -j$(nproc) ${DEFCONFIG}
    - make ARCH=arm64 CROSS_COMPILE=/usr/bin/aarch64-linux-gnu- O=./build -j$(nproc) bindeb-pkg
    - mv linux-*arm64.deb release/${CPU_TYPE}
  artifacts:
    expire_in: 8 hours
    paths:
    - release/*

package:
  stage: package
  tags:
    - amd64
  script:
    - |
      GIT_TAG=$(git describe --tags --no-abbrev)
      TARNAME="${CI_COMMIT_BRANCH}_${CI_COMMIT_SHORT_SHA}.tar"
      FULL_PATH="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/kernel/${GIT_TAG}/${TARNAME}"
      echo "Full path: ${FULL_PATH}"
      tar cf - -C release . | curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file - ${FULL_PATH}

bl1000:
  variables:
    DEFCONFIG: baikal_defconfig
    CPU_TYPE: "bl1000"
  <<: *build_kernel_dfn
