// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2025, Baikal Electronics, JSC
 */

#ifndef __BAIKAL_SMC_H
#define __BAIKAL_SMC_H

#include <linux/arm-smccc.h>

#define BAIKAL_SIP_SMC_FAST_CALL_VAL(func_num) \
	ARM_SMCCC_CALL_VAL(ARM_SMCCC_FAST_CALL, ARM_SMCCC_SMC_64, \
	ARM_SMCCC_OWNER_SIP, (func_num))

#define BAIKAL_SMC_CMU_CMD		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0000)
#define BAIKAL_SMC_PVT_CMD		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0001)
#define BAIKAL_SMC_FLASH_WRITE		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0002)
#define BAIKAL_SMC_FLASH_READ		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0003)
#define BAIKAL_SMC_FLASH_ERASE		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0004)
#define BAIKAL_SMC_FLASH_PUSH		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0005)
#define BAIKAL_SMC_FLASH_PULL		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0006)
#define BAIKAL_SMC_FLASH_POSITION	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0007)
#define BAIKAL_SMC_FLASH_INIT		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0008)
#define BAIKAL_SMC_FLASH_LOCK		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0009)
#define BAIKAL_SMC_PLAT_INFO		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0010)
#define BAIKAL_SMC_VDU_UPDATE		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0100)
#define BAIKAL_SMC_SCP_LOG_DISABLE	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0200)
#define BAIKAL_SMC_SCP_LOG_ENABLE	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0201)
#define BAIKAL_SMC_EFUSE_GET_LOT	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0202)
#define BAIKAL_SMC_EFUSE_GET_SERIAL	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0203)
#define BAIKAL_SMC_EFUSE_GET_MAC	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0204)
#define BAIKAL_SMC_EFUSE_GET_BINNING	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0205)
#define BAIKAL_SMC_EFUSE_GET_PROCESS	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0206)
#define BAIKAL_SMC_EFUSE_GET_PROJECT	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0207)
#define BAIKAL_SMC_EFUSE_GET_REVISION	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0208)
#define BAIKAL_SMC_VDEC_SMMU_SET_CACHE	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0300)
#define BAIKAL_SMC_VDEC_SMMU_GET_CACHE	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0301)
#define BAIKAL_SMC_CLK_ROUND		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0400)
#define BAIKAL_SMC_CLK_SET		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0401)
#define BAIKAL_SMC_CLK_GET		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0402)
#define BAIKAL_SMC_CLK_ENABLE		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0403)
#define BAIKAL_SMC_CLK_DISABLE		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0404)
#define BAIKAL_SMC_CLK_IS_ENABLED	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0405)
#define BAIKAL_SMC_CLK_GET_PARENT	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0406)
#define BAIKAL_SMC_CLK_SET_PARENT	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0407)
#define BAIKAL_SMC_GMAC_DIV2_ENABLE	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0500)
#define BAIKAL_SMC_GMAC_DIV2_DISABLE	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0501)
#define BAIKAL_SMC_RST_SET		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0700)
#define BAIKAL_SMC_RST_CLR		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0701)
#define BAIKAL_SMC_PM			BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0800)
#define BAIKAL_SMC_WDT			BAIKAL_SIP_SMC_FAST_CALL_VAL(0x0900)
#define BAIKAL_SMC_SYSREG_WRITE		BAIKAL_SIP_SMC_FAST_CALL_VAL(0x1100)
#define BAIKAL_SMC_DP_MODELINE_SET	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x1200)
#define BAIKAL_SMC_POWER_DOMAIN_STATE	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x1300)
#define BAIKAL_SMC_POWER_DOMAIN_ON	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x1301)
#define BAIKAL_SMC_POWER_DOMAIN_OFF	BAIKAL_SIP_SMC_FAST_CALL_VAL(0x1302)

#endif
